# Generated by Django 5.1.3 on 2025-01-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feature1',
            new_name='Feature',
        ),
    ]
